name: Trigger auto deployment for container-app-q6j3rkepayt6i

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-q6j3rkepayt6i-AutoDeployTrigger-926ee3d3-2a99-4690-9c38-5d78f7e44195.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQ6J3RKEPAYT6I_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQ6J3RKEPAYT6I_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQ6J3RKEPAYT6I_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPQ6J3RKEPAYT6I_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQ6J3RKEPAYT6I_REGISTRY_PASSWORD }}
          containerAppName: container-app-q6j3rkepayt6i
          resourceGroup: todonodejspgsqlgoogleauth93b79415
          imageToBuild: default/container-app-q6j3rkepayt6i:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


